[package]
name = "pulse-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.pulse-sc]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.60.0"
default-features = false
