// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    pulse_sc
    (
        init => init
        upgrade => upgrade
        set_root_hash => set_root_hash
        newPoll => new_poll
        endPoll => end_poll
        vote_poll => vote_poll
        getPoll => polls
        getPollVotes => poll_votes
        getNextAvailablePollIndex => next_available_poll_index
        getRootHash => root_hash
        getTotalVotes => get_total_votes
        confirmVotingPower => confirm_voting_power
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
